import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClerkProvider
  appearance={{
    // cssLayerName: "clerk",
    layout: {
      logoImageUrl: "/icons/yoom-logo.svg",
      socialButtonsVariant: "iconButton",
    },
    variables: {
      colorText: "#fff",
      colorPrimary: "#0E76F9",
      colorBackground: "#1c1f3e",
      colorInputBackground: "#252a41",
      colorInputText: "#fff",
    },
    elements: {
      userButtonPopoverCard: "bg-[#1c1f3e] text-white border border-[#252a41]",
      userButtonPopoverFooter: "text-gray-400",
      userButtonPopoverActionButton: "text-white hover:text-[#0E76F9]",
      userButtonPopoverActionButtonIcon: "text-white",
      userButtonPopoverActionButtonText: "text-white",
      formButtonPrimary:"text-white",
      userButtonPopoverFooterLink: "text-white hover:text-[#0E76F9]",
      userButtonPopoverFooterText: "text-gray-300",
    },
  }}
>
        <body
          className={`${geistSans.variable} ${inter.className} bg-[#161925] ${geistMono.variable} antialiased`}
        >
          {children}
        </body>
      </ClerkProvider>
    </html>
  );
}
